set -x

    # data.val_files=$HOME/verl/data/test.parquet \
export TMPDIR=$HOME/verl/tmp
export HYDRA_FULL_ERROR=1
save_path=$HOME/verl/output_test
exp_name=qwen2.5-3b_dapo17k_gsm8k_grpo_test
CUDA_VISIBLE_DEVICES=4,5 python3 -m verl.trainer.main_ppo \
    actor_rollout_ref.actor.checkpoint.save_contents=$save_path \
    trainer.n_gpus_per_node=2 \
    algorithm.adv_estimator=grpo \
    data.train_files=/home/yichen/verl/data/dapo17k/train.parquet \
    data.val_files=/home/yichen/verl/data/gsm8k/test.parquet \
    data.train_batch_size=8 \
    data.max_prompt_length=512 \
    data.max_response_length=3072 \
    actor_rollout_ref.rollout.max_num_batched_tokens=3584 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    actor_rollout_ref.model.path=/home/yichen/open-r1/qwen2.5-3b \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=8 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=30 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.75 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=30 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["console"]' \
    trainer.project_name='verl_grpo_example_gsm8k' \
    trainer.experiment_name=$exp_name \
    trainer.nnodes=1 \
    trainer.val_before_train=True \
    trainer.log_val_generations=10 \
    trainer.total_epochs=0 $@

    # trainer.save_freq=20 \
    # trainer.resume_mode=auto \
    # trainer.max_actor_ckpt_to_keep=1 \
    # trainer.max_critic_ckpt_to_keep=1 \